export const endpoints = {
  public: {
    companies: '/public/v1/companies',
  },
  auth: {
    login: '/api/v1/auth/login',
    switchContext: '/api/v1/auth/switch-context',
    me: '/api/v1/auth/me',
    refresh: '/api/v1/auth/refresh',
    logout: '/api/v1/auth/logout',
  },
  dashboard: {
    summary: '/api/v1/dashboard/summary',
    stockByLocation: '/api/v1/dashboard/stock-by-location',
    movementTrend: '/api/v1/dashboard/movement-trend',
    pendingActions: '/api/v1/dashboard/pending-actions',
    audit: '/api/v1/dashboard/audit',
  },
  master: {
    companies: '/api/v1/companies',
    locations: '/api/v1/locations',
    warehouses: '/api/v1/warehouses',
    categoryGroups: '/api/v1/category-groups',
    categories: '/api/v1/categories',
    uoms: '/api/v1/uoms',
    brands: '/api/v1/brands',
    items: '/api/v1/items',
    suppliers: '/api/v1/suppliers',
    divisions: '/api/v1/divisions',
    employees: '/api/v1/employees',
    vehicles: '/api/v1/vehicles',
  },
  procurement: {
    purchaseOrders: '/api/v1/purchase-orders',
    goodsReceipts: '/api/v1/goods-receipts',
    complaints: '/api/v1/complaints',
  },
  inventory: {
    stocks: '/api/v1/inventory/stocks',
    itemUnits: '/api/v1/inventory/item-units',
    stockThresholds: '/api/v1/inventory/stock-thresholds',
    lowStockNotifications: '/api/v1/inventory/low-stock-notifications',
    itemRequests: '/api/v1/item-requests',
    deliveryOrders: '/api/v1/delivery-orders',
    itemUsages: '/api/v1/item-usages',
    stockAdjustments: '/api/v1/stock-adjustments',
    stockOpnames: '/api/v1/stock-opnames',
  },
  approvals: {
    inbox: '/api/v1/approvals/inbox',
  },
  reports: {
    purchaseOrders: '/api/v1/reports/purchase-orders',
    purchaseOrderFulfillment: '/api/v1/reports/purchase-order-fulfillment',
    goodsReceipts: '/api/v1/reports/goods-receipts',
    landedCosts: '/api/v1/reports/landed-costs',
    vendorComplaints: '/api/v1/reports/vendor-complaints',
    supplierPerformance: '/api/v1/reports/supplier-performance',
    postingHistory: '/api/v1/reports/posting-history',
    reversals: '/api/v1/reports/reversals',
    documentStatusHistory: '/api/v1/reports/document-status-history',
    failedTransactions: '/api/v1/reports/failed-transactions',
    stockCorrections: '/api/v1/reports/stock-corrections',
  },
  assets: {
    root: '/api/v1/assets',
    maintenances: '/api/v1/asset-maintenances',
    losses: '/api/v1/asset-loss-cases',
    disposals: '/api/v1/asset-disposals',
    directAcquisitions: '/api/v1/asset-direct-acquisitions',
    migrations: '/api/v1/asset-migrations',
  },
  administration: {
    users: '/api/v1/users',
    roles: '/api/v1/rbac/roles',
    permissions: '/api/v1/rbac/permissions',
    auditLogs: '/api/v1/user-activity/audit-logs',
    loginHistories: '/api/v1/user-activity/login-histories',
    activeSessions: '/api/v1/user-activity/active-sessions',
  },
} as const
