import type { FieldOptionSource } from '@/types/resource'

const option = (path: string, extra: Partial<FieldOptionSource> = {}): FieldOptionSource => ({
  path,
  valueKeys: ['value', 'id'],
  labelKeys: ['label', 'name', 'code'],
  ...extra,
})

export const fieldOptionSources: Record<string, FieldOptionSource> = {
  company_id: option('/api/v1/companies/options'),
  location_type_id: option('/api/v1/location-types/options'),
  location_id: option('/api/v1/locations/options', {
    queryFromModel: { company_id: 'company_id' },
  }),
  location_parent_id: option('/api/v1/locations/options', {
    queryFromModel: { company_id: 'company_id' },
  }),
  responsibility_location_id: option('/api/v1/locations/options'),
  warehouse_id: option('/api/v1/warehouses/options'),
  requester_warehouse_id: option('/api/v1/warehouses/options'),
  from_warehouse_id: option('/api/v1/warehouses/options'),
  to_warehouse_id: option('/api/v1/warehouses/options'),
  category_group_id: option('/api/v1/category-groups/options', {
    queryFromModel: { company_id: 'company_id' },
  }),
  category_group_ids: option('/api/v1/category-groups/options', {
    queryFromModel: { company_id: 'company_id' },
  }),
  category_id: option('/api/v1/categories/options'),
  category_ids: option('/api/v1/categories/options'),
  parent_category_id: option('/api/v1/categories/options'),
  brand_id: option('/api/v1/brands/options'),
  supplier_id: option('/api/v1/suppliers/options'),
  part_id: option('/api/v1/items/{item_id}/part-numbers', {
    pathFromModel: { item_id: 'item_id' },
    valueKeys: ['part_id', 'item_part_number_id', 'id', 'value'],
    labelKeys: ['part_number', 'label', 'name', 'code'],
  }),
  request_id: option('/api/v1/item-requests', {
    valueKeys: ['request_id', 'id'],
    labelKeys: ['request_no', 'reference_no', 'id'],
  }),
  source_request_id: option('/api/v1/item-requests', {
    valueKeys: ['request_id', 'id'],
    labelKeys: ['request_no', 'reference_no', 'id'],
  }),
  receipt_id: option('/api/v1/landed-costs/options/eligible-receipts', {
    valueKeys: ['receipt_id', 'goods_receipt_id', 'id'],
    labelKeys: ['receipt_no', 'vendor_delivery_no', 'id'],
  }),
  goods_receipt_id: option('/api/v1/landed-costs/options/eligible-receipts', {
    valueKeys: ['receipt_id', 'goods_receipt_id', 'id'],
    labelKeys: ['receipt_no', 'vendor_delivery_no', 'id'],
  }),
  unit_id: option('/api/v1/assets', {
    valueKeys: ['unit_id', 'id'],
    labelKeys: ['asset_no', 'qr_code', 'item_name', 'id'],
  }),
  uom_id: option('/api/v1/uoms/options'),
  base_uom_id: option('/api/v1/uoms/options'),
  from_uom_id: option('/api/v1/uoms/options'),
  to_uom_id: option('/api/v1/uoms/options'),
  division_id: option('/api/v1/divisions/options'),
  responsibility_division_id: option('/api/v1/divisions/options'),
  employee_id: option('/api/v1/employees/options'),
  responsibility_employee_id: option('/api/v1/employees/options'),
  vehicle_id: option('/api/v1/vehicles/options'),
  responsibility_vehicle_id: option('/api/v1/vehicles/options'),
  user_id: option('/api/v1/users/options'),
  user_ids: option('/api/v1/users/options'),
  role_id: option('/api/v1/roles/options'),
  role_ids: option('/api/v1/roles/options'),
  permission_id: option('/api/v1/permissions/options'),
  permission_ids: option('/api/v1/permissions/options'),
  responsibility_type: {
    path: '',
    staticOptions: [
      { value: 'EMPLOYEE', label: 'Employee' },
      { value: 'DIVISION', label: 'Division' },
      { value: 'LOCATION', label: 'Location' },
      { value: 'VEHICLE', label: 'Vehicle' },
    ],
  },
  acquisition_type: {
    path: '',
    staticOptions: [
      { value: 'PURCHASE_DIRECT', label: 'Pembelian Langsung' },
      { value: 'HIBAH', label: 'Hibah' },
      { value: 'TRANSFER_IN', label: 'Transfer Masuk' },
      { value: 'OTHER', label: 'Lainnya' },
    ],
  },
  asset_condition: {
    path: '',
    staticOptions: [
      { value: 'NEW', label: 'Baru' },
      { value: 'GOOD', label: 'Baik' },
      { value: 'FAIR', label: 'Cukup' },
      { value: 'DAMAGED', label: 'Rusak' },
      { value: 'UNUSABLE', label: 'Tidak Dapat Digunakan' },
    ],
  },
  tracking_type: {
    path: '',
    staticOptions: [
      { value: 'QTY', label: 'Quantity' },
      { value: 'LOT', label: 'Lot / Batch' },
      { value: 'SERIAL', label: 'Serial / QR' },
    ],
  },
  condition_status: {
    path: '',
    staticOptions: [
      { value: 'NEW', label: 'New' },
      { value: 'GOOD', label: 'Good' },
      { value: 'FAIR', label: 'Fair' },
      { value: 'DAMAGED', label: 'Damaged' },
      { value: 'UNUSABLE', label: 'Unusable' },
    ],
  },
  priority: {
    path: '',
    staticOptions: [
      { value: 'LOW', label: 'Low' },
      { value: 'NORMAL', label: 'Normal' },
      { value: 'HIGH', label: 'High' },
      { value: 'URGENT', label: 'Urgent' },
    ],
  },
  currency_code: {
    path: '',
    staticOptions: [
      { value: 'IDR', label: 'IDR - Rupiah' },
      { value: 'USD', label: 'USD - US Dollar' },
      { value: 'SGD', label: 'SGD - Singapore Dollar' },
      { value: 'EUR', label: 'EUR - Euro' },
    ],
  },
}

export const fieldLabels: Record<string, string> = {
  id: 'ID',
  company_id: 'Company',
  company_code: 'Kode Company',
  company_name: 'Nama Company',
  location_type_id: 'Tipe Lokasi',
  location_type_code: 'Kode Tipe Lokasi',
  location_type_name: 'Nama Tipe Lokasi',
  location_id: 'Location',
  location_code: 'Kode Location',
  location_name: 'Nama Location',
  location_parent_id: 'Parent Location',
  alamat: 'Alamat',
  pemilik: 'Pemilik',
  warehouse_id: 'Warehouse',
  warehouse_code: 'Kode Warehouse',
  warehouse_name: 'Nama Warehouse',
  category_group_id: 'Category Group',
  category_group_ids: 'Category Group',
  category_group_code: 'Kode Category Group',
  category_group_name: 'Nama Category Group',
  category_id: 'Category',
  category_ids: 'Categories',
  category_code: 'Kode Category',
  category_name: 'Nama Category',
  parent_category_id: 'Parent Category',
  uom_id: 'UOM',
  base_uom_id: 'Base UOM',
  from_uom_id: 'From UOM',
  to_uom_id: 'To UOM',
  uom_code: 'Kode UOM',
  uom_name: 'Nama UOM',
  brand_id: 'Brand',
  brand_code: 'Kode Brand',
  brand_name: 'Nama Brand',
  supplier_id: 'Supplier',
  supplier_code: 'Kode Supplier',
  supplier_name: 'Nama Supplier',
  contact_person: 'Contact Person',
  item_id: 'Item',
  item_code: 'Kode Item',
  item_name: 'Nama Item',
  part_id: 'Part Number',
  part_number: 'Part Number',
  item_supplier_id: 'Supplier Item',
  item_part_number_id: 'Item Part Number',
  description: 'Deskripsi',
  notes: 'Catatan',
  is_active: 'Aktif',
  is_primary: 'Utama',
  is_preferred: 'Preferred',
  email: 'Email',
  phone: 'Telepon',
  address: 'Alamat',
  website: 'Website',
  npwp: 'NPWP',
  tracking_type: 'Tracking Type',
  acquisition_type: 'Sumber Perolehan',
  asset_condition: 'Kondisi Aset',
  asset_tag: 'Asset Tag',
  warranty_expired_at: 'Garansi Berakhir',
  requires_serial: 'Wajib Serial',
  has_part_number: 'Memiliki Part Number',
  is_asset: 'Asset',
  asset_category: 'Kategori Asset',
  useful_life_months: 'Umur Manfaat (Bulan)',
  minimum_stock: 'Minimum Stock',
  weight_kg: 'Berat (kg)',
  volume_m3: 'Volume (m³)',
  expected_date: 'Tanggal Diharapkan',
  needed_date: 'Tanggal Dibutuhkan',
  currency_code: 'Mata Uang',
  unit_price: 'Harga Satuan',
  ordered_qty: 'Qty Pesan',
  received_qty: 'Qty Datang',
  accepted_qty: 'Qty Diterima',
  rejected_qty: 'Qty Ditolak',
  requested_qty: 'Qty Permintaan',
  adjustment_qty: 'Qty Penyesuaian',
  qty: 'Qty',
  po_id: 'Purchase Order',
  po_line_id: 'Baris PO',
  invoice_no: 'Nomor Invoice',
  vendor_delivery_no: 'Nomor Surat Jalan Vendor',
  lot_no: 'Lot / Batch',
  condition_status: 'Kondisi',
  rejection_reason: 'Alasan Penolakan',
  purchase_unit_price: 'Harga Pembelian',
  requester_warehouse_id: 'Warehouse Peminta',
  from_warehouse_id: 'Warehouse Asal',
  to_warehouse_id: 'Warehouse Tujuan',
  request_id: 'Permintaan Barang',
  source_request_id: 'Sumber Permintaan Barang',
  request_line_id: 'Baris Permintaan',
  issue_mode: 'Mode Pengeluaran',
  delivery_line_id: 'Baris Surat Jalan',
  complaint_line_id: 'Baris Komplain',
  approved_qty: 'Qty Disetujui',
  action_type: 'Tindakan Penyelesaian',
  return_reference_no: 'Nomor Referensi Retur',
  replacement_reference_no: 'Nomor Referensi Pengganti',
  replacement_receipt_id: 'Penerimaan Barang Pengganti',
  resolution_notes: 'Catatan Penyelesaian',
  shipped_at: 'Tanggal Dikirim',
  received_at: 'Tanggal Diterima',
  assigned_at: 'Tanggal Penugasan',
  expected_return_at: 'Rencana Pengembalian',
  assigned_condition: 'Kondisi Saat Diserahkan',
  handover_notes: 'Catatan Serah Terima',
  tracking_no: 'Nomor Tracking',
  priority: 'Prioritas',
  responsibility_type: 'Tipe Penanggung Jawab',
  responsibility_employee_id: 'Employee',
  responsibility_division_id: 'Division',
  responsibility_location_id: 'Location',
  responsibility_vehicle_id: 'Vehicle',
  used_by_name: 'Digunakan Oleh',
  usage_type: 'Tipe Penggunaan',
  reference_no: 'Nomor Referensi',
  asset_no: 'Nomor Asset',
  reason: 'Alasan',
  scan_code: 'Kode Scan / QR',
  qr_code: 'QR Code',
  serial_number: 'Serial Number',
  device_id: 'Device ID',
  app_version: 'App Version',
  full_name: 'Nama Lengkap',
  nib: 'NIB',
  password: 'Password',
  code: 'Kode',
  name: 'Nama',
  role_ids: 'Roles',
  permission_ids: 'Permissions',
  user_ids: 'Users',
  registration_no: 'Nomor Polisi',
  vehicle_code: 'Kode Kendaraan',
  vehicle_name: 'Nama Kendaraan',
  vehicle_type: 'Tipe Kendaraan',
  manufacture_year: 'Tahun Produksi',
  model: 'Model',
  brand: 'Brand',
}

export function humanizeField(value: string): string {
  return (
    fieldLabels[value] ?? value.replaceAll('_', ' ').replace(/\b\w/g, (char) => char.toUpperCase())
  )
}
