import type { ApiSchema } from '@/types/resource'

const sharedCrudOrders: Record<string, string[]> = {
  CreateCompany: ['company_code', 'company_name', 'is_active'],
  UpdateCompany: ['company_code', 'company_name', 'is_active'],
  CreateLocationType: ['location_type_code', 'location_type_name', 'is_active'],
  UpdateLocationType: ['location_type_code', 'location_type_name', 'is_active'],
  CreateLocation: [
    'company_id',
    'location_code',
    'location_name',
    'location_type_id',
    'is_active',
    'location_parent_id',
    'pemilik',
    'alamat',
  ],
  UpdateLocation: [
    'company_id',
    'location_code',
    'location_name',
    'location_type_id',
    'is_active',
    'location_parent_id',
    'pemilik',
    'alamat',
  ],
  CreateWarehouse: ['location_id', 'warehouse_code', 'warehouse_name', 'is_active', 'description'],
  UpdateWarehouse: ['warehouse_code', 'warehouse_name', 'is_active', 'description'],
  CreateVehicle: [
    'location_id',
    'division_id',
    'vehicle_code',
    'registration_no',
    'vehicle_name',
    'vehicle_type',
    'brand',
    'model',
    'manufacture_year',
    'is_active',
  ],
  UpdateVehicle: [
    'location_id',
    'division_id',
    'vehicle_code',
    'registration_no',
    'vehicle_name',
    'vehicle_type',
    'brand',
    'model',
    'manufacture_year',
    'is_active',
  ],
  CreateCategoryGroup: [
    'category_group_code',
    'category_group_name',
    'category_ids',
    'is_active',
    'description',
  ],
  UpdateCategoryGroup: [
    'category_group_code',
    'category_group_name',
    'category_ids',
    'is_active',
    'description',
  ],
  CreateCategory: [
    'parent_category_id',
    'category_code',
    'category_name',
    'is_active',
    'description',
  ],
  UpdateCategory: [
    'parent_category_id',
    'category_code',
    'category_name',
    'is_active',
    'description',
  ],
  CreateUOM: ['uom_code', 'uom_name', 'is_active', 'description'],
  UpdateUOM: ['uom_code', 'uom_name', 'is_active', 'description'],
  CreateBrand: ['brand_code', 'brand_name', 'is_active', 'description'],
  UpdateBrand: ['brand_code', 'brand_name', 'is_active', 'description'],
  CreateSupplier: [
    'supplier_code',
    'supplier_name',
    'contact_person',
    'phone',
    'email',
    'npwp',
    'website',
    'is_active',
    'address',
    'notes',
  ],
  UpdateSupplier: [
    'supplier_code',
    'supplier_name',
    'contact_person',
    'phone',
    'email',
    'npwp',
    'website',
    'is_active',
    'address',
    'notes',
  ],
  CreateItem: [
    'item_code',
    'item_name',
    'category_id',
    'brand_id',
    'base_uom_id',
    'tracking_type',
    'has_part_number',
    'requires_serial',
    'is_asset',
    'asset_category',
    'minimum_stock',
    'weight_kg',
    'volume_m3',
    'useful_life_months',
    'is_active',
    'description',
  ],
  UpdateItem: [
    'item_code',
    'item_name',
    'category_id',
    'brand_id',
    'base_uom_id',
    'tracking_type',
    'has_part_number',
    'requires_serial',
    'is_asset',
    'asset_category',
    'minimum_stock',
    'weight_kg',
    'volume_m3',
    'useful_life_months',
    'is_active',
    'description',
  ],
  CreateItemPartNumber: ['item_id', 'part_number', 'barcode', 'is_active', 'description'],
  UpdateItemPartNumber: ['item_id', 'part_number', 'barcode', 'is_active', 'description'],
  CreateItemSupplier: [
    'item_id',
    'supplier_id',
    'supplier_item_code',
    'last_purchase_price',
    'is_default',
    'is_active',
    'notes',
  ],
  UpdateItemSupplier: [
    'item_id',
    'supplier_id',
    'supplier_item_code',
    'last_purchase_price',
    'is_default',
    'is_active',
    'notes',
  ],
  CreateItemUOMConversion: [
    'item_id',
    'from_uom_id',
    'to_uom_id',
    'multiplier',
    'is_active',
    'description',
  ],
  UpdateItemUOMConversion: [
    'item_id',
    'from_uom_id',
    'to_uom_id',
    'multiplier',
    'is_active',
    'description',
  ],
  CreatePurchasePrice: [
    'item_id',
    'part_id',
    'supplier_id',
    'uom_id',
    'currency_code',
    'unit_price',
    'effective_from',
    'notes',
  ],
  UpdatePurchasePrice: ['currency_code', 'unit_price', 'effective_from', 'notes'],
  CreateUser: ['nib', 'full_name', 'email', 'password', 'is_active'],
  UpdateUser: ['nib', 'full_name', 'email', 'is_active'],
  CreateRole: ['code', 'name', 'description'],
  UpdateRole: ['code', 'name', 'description'],
  CreatePermission: ['code', 'name', 'description'],
  UpdatePermission: ['code', 'name', 'description'],
}

const transactionOrders: Record<string, string[]> = {
  CreatePurchaseOrder: [
    'warehouse_id',
    'supplier_id',
    'source_request_id',
    'expected_date',
    'currency_code',
    'lines',
    'notes',
  ],
  UpdatePurchaseOrder: [
    'warehouse_id',
    'supplier_id',
    'source_request_id',
    'expected_date',
    'currency_code',
    'lines',
    'notes',
  ],
  CreateGoodsReceipt: [
    'warehouse_id',
    'po_id',
    'supplier_id',
    'vendor_delivery_no',
    'invoice_no',
    'lines',
    'notes',
  ],
  UpdateGoodsReceiptHeader: ['vendor_delivery_no', 'invoice_no', 'notes'],
  UpdateGoodsReceiptLines: ['lines'],
  CreateItemRequest: ['requester_warehouse_id', 'needed_date', 'priority', 'lines', 'notes'],
  UpdateItemRequest: ['requester_warehouse_id', 'needed_date', 'priority', 'lines', 'notes'],
  CreateDeliveryOrder: [
    'request_id',
    'from_warehouse_id',
    'to_warehouse_id',
    'tracking_no',
    'lines',
    'notes',
  ],
  CreateItemUsage: [
    'issue_mode',
    'source_request_id',
    'warehouse_id',
    'location_id',
    'reference_no',
    'usage_type',
    'responsibility_type',
    'responsibility_employee_id',
    'responsibility_division_id',
    'responsibility_location_id',
    'responsibility_vehicle_id',
    'used_by_name',
    'asset_no',
    'lines',
    'notes',
  ],
  UpdateItemUsage: [
    'issue_mode',
    'source_request_id',
    'warehouse_id',
    'location_id',
    'reference_no',
    'usage_type',
    'responsibility_type',
    'responsibility_employee_id',
    'responsibility_division_id',
    'responsibility_location_id',
    'responsibility_vehicle_id',
    'used_by_name',
    'asset_no',
    'lines',
    'notes',
  ],
  CreateStockAdjustment: ['warehouse_id', 'reason', 'lines', 'notes'],
  CreateStockOpname: ['warehouse_id', 'notes'],
  CreateStockThreshold: [
    'warehouse_id',
    'location_id',
    'item_id',
    'part_id',
    'uom_id',
    'lot_no',
    'minimum_stock',
    'maximum_stock',
    'reorder_point',
    'reorder_qty',
    'is_active',
    'notes',
  ],
  UpdateStockThreshold: [
    'warehouse_id',
    'location_id',
    'item_id',
    'part_id',
    'uom_id',
    'lot_no',
    'minimum_stock',
    'maximum_stock',
    'reorder_point',
    'reorder_qty',
    'is_active',
    'notes',
  ],
  CreateComplaint: [
    'source_type',
    'source_id',
    'reported_by_location_id',
    'complaint_type',
    'lines',
    'description',
  ],
  Create: [
    'document_date',
    'currency_code',
    'default_allocation_method',
    'receipt_ids',
    'charges',
    'notes',
  ],
  Update: [
    'document_date',
    'currency_code',
    'default_allocation_method',
    'receipt_ids',
    'charges',
    'notes',
  ],
}

const workflowOrders: Record<string, string[]> = {
  CreateMaintenance: [
    'maintenance_type',
    'supplier_id',
    'estimated_cost',
    'problem_description',
    'notes',
  ],
  CreateDisposal: ['disposal_method', 'buyer_name', 'proceeds', 'reason', 'notes'],
  CreateHandover: ['entity_type', 'entity_id', 'document_type', 'title', 'notes'],
}

export const operationFieldOrders: Record<string, string[]> = {
  ...sharedCrudOrders,
  ...transactionOrders,
  ...workflowOrders,
}

function semanticRank(field: string): number {
  if (/^(company|location|warehouse|division|employee|supplier|item|category).*_id$/.test(field))
    return 10
  if (/(_code|_no|^code$|^nib$|^email$)/.test(field)) return 20
  if (/(_name|^name$|^title$)/.test(field)) return 30
  if (/(_type|_category|_method|_status|priority|currency)/.test(field)) return 40
  if (/(_date|_at|year|month)/.test(field)) return 50
  if (/(qty|price|cost|amount|stock|weight|volume|multiplier|proceeds)/.test(field)) return 60
  if (/^(lines|items|charges|receipt_ids)$/.test(field)) return 70
  if (/^(is_|has_|requires_)/.test(field)) return 80
  if (/(address|alamat|description|notes|reason|remarks|findings)$/.test(field)) return 90
  return 45
}

export function resolveOperationFieldOrder(
  operationId: string | undefined,
  schema?: ApiSchema,
): string[] {
  if (operationId && operationFieldOrders[operationId]) return operationFieldOrders[operationId]
  return Object.keys(schema?.properties ?? {}).sort((left, right) => {
    const rank = semanticRank(left) - semanticRank(right)
    return rank || left.localeCompare(right, 'id-ID')
  })
}
