import type { ResourceModuleDefinition } from '@/types/resource'

const crud = (definition: ResourceModuleDefinition): ResourceModuleDefinition => ({
  idCandidates: ['id', 'uuid'],
  statusCandidates: ['status', 'is_active'],
  ...definition,
})

export const resourceModules: Record<string, ResourceModuleDefinition> = {
  companies: crud({
    key: 'companies',
    title: 'Perusahaan',
    description: 'Kelola perusahaan dalam AIMS.',
    group: 'Organisasi',
    route: '/organization/companies',
    listOperationId: 'FindAllCompaniesPrivate',
    detailOperationId: 'FindCompanyByIDPrivate',
    createOperationId: 'CreateCompany',
    updateOperationId: 'UpdateCompany',
    deleteOperationId: 'DeleteCompany',
    readPermission: 'organization.companies.read',
    createPermission: 'organization.companies.create',
    updatePermission: 'organization.companies.update',
    deletePermission: 'organization.companies.delete',
    superAdminOnly: true,
    columns: ['company_code', 'company_name', 'is_active', 'created_at', 'updated_at'],
    idCandidates: ['id_company', 'company_id', 'id'],
  }),
  'location-types': crud({
    key: 'location-types',
    title: 'Tipe Lokasi',
    description: 'Kelola tipe lokasi operasional.',
    group: 'Organisasi',
    route: '/organization/location-types',
    listOperationId: 'FindAllLocationTypesPrivate',
    detailOperationId: 'FindLocationTypeByIDPrivate',
    createOperationId: 'CreateLocationType',
    updateOperationId: 'UpdateLocationType',
    deleteOperationId: 'DeleteLocationType',
    readPermission: 'organization.location_types.read',
    createPermission: 'organization.location_types.create',
    updatePermission: 'organization.location_types.update',
    deletePermission: 'organization.location_types.delete',
    columns: ['location_type_code', 'location_type_name', 'description', 'is_active'],
    idCandidates: ['location_type_id', 'id'],
  }),
  locations: crud({
    key: 'locations',
    title: 'Lokasi',
    description: 'Kelola lokasi dan hierarki lokasi perusahaan.',
    group: 'Organisasi',
    route: '/organization/locations',
    listOperationId: 'FindAllLocationsPrivate',
    detailOperationId: 'FindLocationByIDPrivate',
    createOperationId: 'CreateLocation',
    updateOperationId: 'UpdateLocation',
    deleteOperationId: 'DeleteLocation',
    readPermission: 'organization.locations.read',
    createPermission: 'organization.locations.create',
    updatePermission: 'organization.locations.update',
    deletePermission: 'organization.locations.delete',
    columns: [
      'location_code',
      'location_name',
      'company_name',
      'location_type_name',
      'alamat',
      'is_active',
    ],
    idCandidates: ['location_id', 'id'],
  }),
  warehouses: crud({
    key: 'warehouses',
    title: 'Gudang',
    description: 'Kelola gudang per lokasi.',
    group: 'Organisasi',
    route: '/organization/warehouses',
    listOperationId: 'FindAllWarehouses',
    detailOperationId: 'FindWarehouseByID',
    createOperationId: 'CreateWarehouse',
    updateOperationId: 'UpdateWarehouse',
    deleteOperationId: 'DeleteWarehouse',
    readPermission: 'warehouse.warehouses.read',
    createPermission: 'warehouse.warehouses.create',
    updatePermission: 'warehouse.warehouses.update',
    deletePermission: 'warehouse.warehouses.delete',
    columns: ['warehouse_code', 'warehouse_name', 'location_name', 'description', 'is_active'],
    idCandidates: ['warehouse_id', 'id'],
  }),
  divisions: crud({
    key: 'divisions',
    title: 'Division',
    description: 'Data divisi hasil sinkronisasi HRIS.',
    group: 'Organisasi',
    route: '/organization/divisions',
    listOperationId: 'FindAllDivisions',
    detailOperationId: 'FindDivisionByID',
    readPermission: 'organization.divisions.read',
    readOnly: true,
    columns: ['division_code', 'division_name', 'company_name', 'is_active'],
    idCandidates: ['division_id', 'id'],
  }),
  employees: crud({
    key: 'employees',
    title: 'Employee',
    description: 'Data karyawan sebagai target tanggung jawab.',
    group: 'Organisasi',
    route: '/organization/employees',
    listOperationId: 'FindAllEmployees',
    detailOperationId: 'FindEmployeeByID',
    readPermission: 'organization.employees.read',
    readOnly: true,
    columns: ['nib', 'employee_name', 'division_name', 'location_name', 'is_active'],
    idCandidates: ['employee_id', 'id'],
  }),
  responsibilities: crud({
    key: 'responsibilities',
    title: 'Responsibility Directory',
    description:
      'Direktori gabungan location, division, employee, dan vehicle dalam context aktif.',
    group: 'Organisasi',
    route: '/organization/responsibilities',
    listOperationId: 'FindResponsibilityOptions',
    readPermission: 'organization.responsibilities.read',
    readOnly: true,
    columns: ['type', 'code', 'name', 'secondary', 'location_id', 'is_active'],
    idCandidates: ['id'],
  }),
  vehicles: crud({
    key: 'vehicles',
    title: 'Vehicle',
    description: 'Kelola kendaraan sebagai target penggunaan dan tanggung jawab.',
    group: 'Organisasi',
    route: '/organization/vehicles',
    listOperationId: 'FindAllVehicles',
    detailOperationId: 'FindVehicleByID',
    createOperationId: 'CreateVehicle',
    updateOperationId: 'UpdateVehicle',
    deleteOperationId: 'DeleteVehicle',
    readPermission: 'organization.vehicles.read',
    createPermission: 'organization.vehicles.create',
    updatePermission: 'organization.vehicles.update',
    deletePermission: 'organization.vehicles.delete',
    columns: [
      'registration_no',
      'vehicle_code',
      'vehicle_name',
      'vehicle_type',
      'brand',
      'model',
      'is_active',
    ],
    idCandidates: ['vehicle_id', 'id'],
  }),

  'category-groups': crud({
    key: 'category-groups',
    title: 'Kelompok Kategori',
    description: 'Kelola kelompok kategori dan pembatasan context.',
    group: 'Katalog',
    route: '/catalog/category-groups',
    listOperationId: 'FindAllCategoryGroups',
    detailOperationId: 'FindCategoryGroupByID',
    createOperationId: 'CreateCategoryGroup',
    updateOperationId: 'UpdateCategoryGroup',
    deleteOperationId: 'DeleteCategoryGroup',
    readPermission: 'catalog.category_groups.read',
    createPermission: 'catalog.category_groups.create',
    updatePermission: 'catalog.category_groups.update',
    deletePermission: 'catalog.category_groups.delete',
    superAdminOnly: true,
    columns: ['category_group_code', 'category_group_name', 'description', 'is_active'],
    idCandidates: ['category_group_id', 'id'],
    detailActions: [
      {
        operationId: 'ReplaceCategoryGroupCategories',
        label: 'Atur Ulang Kategori',
        permission: 'catalog.category_groups.update',
      },
    ],
    childSections: [
      {
        title: 'Kategori dalam Group',
        operationId: 'FindCategoryGroupCategories',
        permission: 'catalog.category_groups.read',
      },
    ],
  }),
  categories: crud({
    key: 'categories',
    title: 'Kategori',
    description: 'Kelola kategori item dan aset.',
    group: 'Katalog',
    route: '/catalog/categories',
    listOperationId: 'FindAllCategories',
    detailOperationId: 'FindCategoryByID',
    createOperationId: 'CreateCategory',
    updateOperationId: 'UpdateCategory',
    deleteOperationId: 'DeleteCategory',
    readPermission: 'catalog.categories.read',
    createPermission: 'catalog.categories.create',
    updatePermission: 'catalog.categories.update',
    deletePermission: 'catalog.categories.delete',
    columns: ['category_code', 'category_name', 'parent_category_name', 'description', 'is_active'],
    idCandidates: ['category_id', 'id'],
  }),
  uoms: crud({
    key: 'uoms',
    title: 'Unit of Measure',
    description: 'Kelola satuan item.',
    group: 'Katalog',
    route: '/catalog/uoms',
    listOperationId: 'FindAllUOMs',
    detailOperationId: 'FindUOMByID',
    createOperationId: 'CreateUOM',
    updateOperationId: 'UpdateUOM',
    deleteOperationId: 'DeleteUOM',
    readPermission: 'catalog.uoms.read',
    createPermission: 'catalog.uoms.create',
    updatePermission: 'catalog.uoms.update',
    deletePermission: 'catalog.uoms.delete',
    columns: ['uom_code', 'uom_name', 'description', 'is_active'],
    idCandidates: ['uom_id', 'id'],
  }),
  brands: crud({
    key: 'brands',
    title: 'Merek',
    description: 'Kelola merek item dan aset.',
    group: 'Katalog',
    route: '/catalog/brands',
    listOperationId: 'FindAllBrands',
    detailOperationId: 'FindBrandByID',
    createOperationId: 'CreateBrand',
    updateOperationId: 'UpdateBrand',
    deleteOperationId: 'DeleteBrand',
    readPermission: 'catalog.brands.read',
    createPermission: 'catalog.brands.create',
    updatePermission: 'catalog.brands.update',
    deletePermission: 'catalog.brands.delete',
    columns: ['brand_code', 'brand_name', 'description', 'is_active'],
    idCandidates: ['brand_id', 'id'],
  }),
  suppliers: crud({
    key: 'suppliers',
    title: 'Pemasok',
    description: 'Kelola supplier dan informasi kontak.',
    group: 'Katalog',
    route: '/catalog/suppliers',
    listOperationId: 'FindAllSuppliers',
    detailOperationId: 'FindSupplierByID',
    createOperationId: 'CreateSupplier',
    updateOperationId: 'UpdateSupplier',
    deleteOperationId: 'DeleteSupplier',
    readPermission: 'catalog.suppliers.read',
    createPermission: 'catalog.suppliers.create',
    updatePermission: 'catalog.suppliers.update',
    deletePermission: 'catalog.suppliers.delete',
    columns: ['supplier_code', 'supplier_name', 'contact_person', 'phone', 'email', 'is_active'],
    idCandidates: ['supplier_id', 'id'],
    childSections: [
      {
        title: 'Barang Pemasok',
        operationId: 'FindItemSuppliersBySupplierID',
        permission: 'catalog.item_suppliers.read',
      },
    ],
  }),
  items: crud({
    key: 'items',
    title: 'Barang',
    description: 'Kelola item, tracking, part number, UOM, dan supplier.',
    group: 'Katalog',
    route: '/catalog/items',
    listOperationId: 'FindAllItems',
    detailOperationId: 'FindItemByID',
    createOperationId: 'CreateItem',
    updateOperationId: 'UpdateItem',
    deleteOperationId: 'DeleteItem',
    readPermission: 'catalog.items.read',
    createPermission: 'catalog.items.create',
    updatePermission: 'catalog.items.update',
    deletePermission: 'catalog.items.delete',
    columns: [
      'item_code',
      'item_name',
      'category_name',
      'brand_name',
      'tracking_type',
      'is_asset',
      'is_active',
    ],
    idCandidates: ['item_id', 'id'],
    childSections: [
      {
        title: 'Part Number',
        operationId: 'FindItemPartNumbersByItemID',
        permission: 'catalog.item_part_numbers.read',
      },
      {
        title: 'Konversi UOM',
        operationId: 'FindItemUOMConversionsByItemID',
        permission: 'catalog.item_uom_conversions.read',
      },
      {
        title: 'Barang Pemasok',
        operationId: 'FindItemSuppliersByItemID',
        permission: 'catalog.item_suppliers.read',
      },
    ],
  }),
  'item-part-numbers': crud({
    key: 'item-part-numbers',
    title: 'Nomor Part Barang',
    description: 'Kelola banyak part number pada satu item.',
    group: 'Katalog',
    route: '/catalog/item-part-numbers',
    listOperationId: 'FindAllItemPartNumbers',
    detailOperationId: 'FindItemPartNumberByID',
    createOperationId: 'CreateItemPartNumber',
    updateOperationId: 'UpdateItemPartNumber',
    deleteOperationId: 'DeleteItemPartNumber',
    readPermission: 'catalog.item_part_numbers.read',
    createPermission: 'catalog.item_part_numbers.create',
    updatePermission: 'catalog.item_part_numbers.update',
    deletePermission: 'catalog.item_part_numbers.delete',
    columns: ['item_name', 'part_number', 'description', 'is_primary', 'is_active'],
    idCandidates: ['part_id', 'item_part_number_id', 'id'],
  }),
  'item-uom-conversions': crud({
    key: 'item-uom-conversions',
    title: 'Konversi Satuan Barang',
    description: 'Kelola konversi satuan per item.',
    group: 'Katalog',
    route: '/catalog/item-uom-conversions',
    listOperationId: 'FindAllItemUOMConversions',
    detailOperationId: 'FindItemUOMConversionByID',
    createOperationId: 'CreateItemUOMConversion',
    updateOperationId: 'UpdateItemUOMConversion',
    deleteOperationId: 'DeleteItemUOMConversion',
    readPermission: 'catalog.item_uom_conversions.read',
    createPermission: 'catalog.item_uom_conversions.create',
    updatePermission: 'catalog.item_uom_conversions.update',
    deletePermission: 'catalog.item_uom_conversions.delete',
    columns: ['item_name', 'from_uom_name', 'to_uom_name', 'conversion_factor', 'is_active'],
    idCandidates: ['conversion_id', 'id'],
  }),
  'item-suppliers': crud({
    key: 'item-suppliers',
    title: 'Barang Pemasok',
    description: 'Kelola relasi item dan supplier.',
    group: 'Katalog',
    route: '/catalog/item-suppliers',
    listOperationId: 'FindAllItemSuppliers',
    detailOperationId: 'FindItemSupplierByID',
    createOperationId: 'CreateItemSupplier',
    updateOperationId: 'UpdateItemSupplier',
    deleteOperationId: 'DeleteItemSupplier',
    readPermission: 'catalog.item_suppliers.read',
    createPermission: 'catalog.item_suppliers.create',
    updatePermission: 'catalog.item_suppliers.update',
    deletePermission: 'catalog.item_suppliers.delete',
    columns: [
      'item_name',
      'supplier_name',
      'supplier_part_number',
      'lead_time_days',
      'is_preferred',
      'is_active',
    ],
    idCandidates: ['item_supplier_id', 'id'],
  }),
  'purchase-prices': crud({
    key: 'purchase-prices',
    title: 'Harga Pembelian',
    description: 'Histori dan referensi harga pembelian supplier.',
    group: 'Katalog',
    route: '/catalog/purchase-prices',
    listOperationId: 'ListPurchasePrices',
    detailOperationId: 'FindPurchasePrice',
    createOperationId: 'CreatePurchasePrice',
    updateOperationId: 'UpdatePurchasePrice',
    deleteOperationId: 'DeletePurchasePrice',
    readPermission: 'catalog.purchase_prices.read',
    createPermission: 'catalog.purchase_prices.create',
    updatePermission: 'catalog.purchase_prices.update',
    deletePermission: 'catalog.purchase_prices.delete',
    columns: [
      'item_name',
      'supplier_name',
      'part_number',
      'uom_name',
      'unit_price',
      'currency_code',
      'effective_date',
    ],
    idCandidates: ['purchase_price_id', 'id'],
  }),

  'purchase-orders': crud({
    key: 'purchase-orders',
    title: 'Pesanan Pembelian',
    description: 'Buat, setujui, finalisasi, dan pantau pemenuhan PO.',
    group: 'Pembelian',
    route: '/procurement/purchase-orders',
    listOperationId: 'FindAllPurchaseOrders',
    detailOperationId: 'FindPurchaseOrderByID',
    createOperationId: 'CreatePurchaseOrder',
    updateOperationId: 'UpdatePurchaseOrder',
    readPermission: 'transaction.purchase_orders.read',
    createPermission: 'transaction.purchase_orders.create',
    updatePermission: 'transaction.purchase_orders.update',
    columns: [
      'po_no',
      'supplier_name',
      'warehouse_name',
      'expected_date',
      'total_amount',
      'currency_code',
      'status',
    ],
    idCandidates: ['po_id', 'id'],
    attachmentEntityType: 'PURCHASE_ORDER',
    createOptionDefaults: { warehouse_id: 'WH-PST' },
    editableStatuses: ['DRAFT'],
    listViews: [
      { key: 'open', label: 'Proses Aktif', query: { lifecycle: 'open' } },
      { key: 'history', label: 'Riwayat Selesai', query: { lifecycle: 'history' } },
      { key: 'all', label: 'Semua', query: { lifecycle: 'all' } },
    ],
    actions: [
      {
        operationId: 'ApprovePurchaseOrder',
        label: 'Setujui',
        permission: 'transaction.purchase_orders.approve',
        statuses: ['DRAFT'],
        confirm: 'Setujui Pesanan Pembelian ini?',
      },
      {
        operationId: 'SendPurchaseOrder',
        label: 'Finalisasi PO',
        permission: 'transaction.purchase_orders.send',
        statuses: ['APPROVED'],
        confirm: 'Finalisasi PO agar dapat digunakan pada penerimaan barang?',
        successMessage: 'PO sudah difinalisasi dan siap diterima.',
      },
      {
        operationId: 'MarkPurchaseOrderVendorProcessing',
        label: 'Vendor Memproses',
        permission: 'transaction.purchase_orders.mark_vendor_processing',
        statuses: ['SENT_TO_VENDOR', 'INDENT'],
        confirm: 'Ubah status PO menjadi sedang diproses vendor?',
      },
      {
        operationId: 'MarkPurchaseOrderReady',
        label: 'Barang Siap dari Vendor',
        permission: 'transaction.purchase_orders.mark_ready',
        statuses: ['SENT_TO_VENDOR', 'VENDOR_PROCESSING', 'INDENT'],
        confirm: 'Tandai barang vendor sudah siap dikirim atau diterima?',
      },
      {
        operationId: 'MarkPurchaseOrderIndent',
        label: 'Tandai Indent',
        permission: 'transaction.purchase_orders.mark_indent',
        statuses: ['SENT_TO_VENDOR', 'VENDOR_PROCESSING'],
        tone: 'secondary',
      },
      {
        operationId: 'RejectPurchaseOrder',
        label: 'Tolak',
        permission: 'transaction.purchase_orders.reject',
        statuses: ['DRAFT', 'APPROVED'],
        tone: 'danger',
      },
      {
        operationId: 'CancelPurchaseOrder',
        label: 'Batalkan',
        permission: 'transaction.purchase_orders.cancel',
        statuses: ['DRAFT', 'APPROVED', 'SENT_TO_VENDOR', 'VENDOR_PROCESSING', 'READY', 'INDENT'],
        tone: 'danger',
      },
      {
        operationId: 'ClosePurchaseOrder',
        label: 'Close',
        permission: 'transaction.purchase_orders.close',
        statuses: [
          'SENT_TO_VENDOR',
          'VENDOR_PROCESSING',
          'READY',
          'INDENT',
          'PARTIAL_RECEIVED',
          'RECEIVED',
        ],
      },
    ],
  }),
  'goods-receipts': crud({
    key: 'goods-receipts',
    title: 'Penerimaan Barang',
    description: 'Pemeriksaan barang, pembuatan QR, dan posting ke stok.',
    group: 'Pembelian',
    route: '/procurement/goods-receipts',
    listOperationId: 'FindAllGoodsReceipts',
    detailOperationId: 'FindGoodsReceiptByID',
    createOperationId: 'CreateGoodsReceipt',
    updateOperationId: 'UpdateGoodsReceiptHeader',
    readPermission: 'transaction.goods_receipts.read',
    createPermission: 'transaction.goods_receipts.create',
    updatePermission: 'transaction.goods_receipts.update',
    columns: ['receipt_no', 'po_no', 'supplier_name', 'warehouse_name', 'receipt_date', 'status'],
    idCandidates: ['receipt_id', 'goods_receipt_id', 'id'],
    attachmentEntityType: 'GOODS_RECEIPT',
    editableStatuses: ['DRAFT', 'RECEIVED', 'ACCEPTED', 'PARTIAL_ACCEPTED', 'REJECTED', 'CHECKING'],
    listViews: [
      { key: 'open', label: 'Proses Aktif', query: { lifecycle: 'open' } },
      { key: 'history', label: 'Sudah Diposting / Riwayat', query: { lifecycle: 'history' } },
      { key: 'all', label: 'Semua', query: { lifecycle: 'all' } },
    ],
    actions: [
      {
        operationId: 'CheckGoodsReceipt',
        label: 'Check',
        permission: 'transaction.goods_receipts.check',
        statuses: ['RECEIVED', 'ACCEPTED', 'PARTIAL_ACCEPTED', 'REJECTED'],
      },
      {
        operationId: 'PreviewGoodsReceiptScan',
        label: 'Scan Masuk',
        permission: 'transaction.goods_receipts.scan',
        handler: 'goods-receipt-scan-in',
        statuses: ['CHECKED'],
      },
      {
        operationId: 'UpdateGoodsReceiptLines',
        label: 'Perbarui Hasil Pemeriksaan',
        permission: 'transaction.goods_receipts.update',
        statuses: ['RECEIVED', 'ACCEPTED', 'PARTIAL_ACCEPTED', 'REJECTED', 'CHECKING'],
      },
      {
        operationId: 'CancelGoodsReceipt',
        label: 'Cancel',
        permission: 'transaction.goods_receipts.cancel',
        hideStatuses: ['POSTED_TO_STOCK', 'CANCELLED', 'REVERSED'],
        tone: 'danger',
      },
    ],
    detailActions: [
      {
        operationId: 'ReverseGoodsReceipt',
        label: 'Balikkan Posting (Koreksi)',
        permission: 'transaction.goods_receipts.reverse',
        statuses: ['POSTED_TO_STOCK'],
        tone: 'danger',
        confirm:
          'Reverse posting ini? Stok dan cost akan dikembalikan melalui transaksi koreksi dan aktivitas akan tercatat pada audit log.',
      },
    ],
  }),
  complaints: crud({
    key: 'complaints',
    title: 'Komplain Vendor',
    description: 'Kelola komplain barang kepada supplier.',
    group: 'Pembelian',
    route: '/procurement/complaints',
    listOperationId: 'FindAllComplaints',
    detailOperationId: 'FindComplaintByID',
    createOperationId: 'CreateComplaint',
    readPermission: 'transaction.complaints.read',
    createPermission: 'transaction.complaints.create',
    updatePermission: 'transaction.complaints.update',
    columns: [
      'complaint_no',
      'supplier_name',
      'receipt_no',
      'complaint_type',
      'status',
      'created_at',
    ],
    idCandidates: ['complaint_id', 'id'],
    attachmentEntityType: 'COMPLAINT',
    actions: [
      {
        operationId: 'ReviewComplaint',
        label: 'Mulai Review',
        permission: 'transaction.complaints.review',
        statuses: ['OPEN'],
      },
      {
        operationId: 'ApproveComplaintReturn',
        label: 'Setujui Retur / Penggantian',
        permission: 'transaction.complaints.approve_return',
        statuses: ['UNDER_REVIEW'],
      },
      {
        operationId: 'ResolveComplaint',
        label: 'Selesaikan Tanpa Retur',
        permission: 'transaction.complaints.resolve',
        statuses: ['UNDER_REVIEW'],
      },
      {
        operationId: 'RejectComplaint',
        label: 'Tolak Komplain',
        permission: 'transaction.complaints.reject',
        statuses: ['UNDER_REVIEW'],
        tone: 'danger',
      },
      {
        operationId: 'RegisterComplaintReturn',
        label: 'Catat Pengiriman Retur',
        permission: 'transaction.complaints.register_return',
        statuses: ['APPROVED_RETURN'],
      },
      {
        operationId: 'StartComplaintReplacement',
        label: 'Mulai Proses Penggantian',
        permission: 'transaction.complaints.start_replacement',
        statuses: ['APPROVED_RETURN'],
      },
      {
        operationId: 'MarkComplaintReplacementShipped',
        label: 'Tandai Pengganti Dikirim',
        permission: 'transaction.complaints.mark_replacement_shipped',
        statuses: ['REPLACEMENT_PROCESS'],
      },
      {
        operationId: 'ConfirmComplaintReplacement',
        label: 'Konfirmasi Barang Pengganti',
        permission: 'transaction.complaints.confirm_replacement',
        statuses: ['REPLACEMENT_SHIPPED'],
      },
    ],
  }),
  'landed-costs': crud({
    key: 'landed-costs',
    title: 'Biaya Perolehan',
    description: 'Alokasikan biaya tambahan ke penerimaan barang dan nilai inventory.',
    group: 'Pembelian',
    route: '/procurement/landed-costs',
    listOperationId: 'List',
    detailOperationId: 'FindByID',
    createOperationId: 'Create',
    updateOperationId: 'Update',
    deleteOperationId: 'Delete',
    readPermission: 'transaction.landed_costs.read',
    createPermission: 'transaction.landed_costs.create',
    updatePermission: 'transaction.landed_costs.update',
    deletePermission: 'transaction.landed_costs.delete',
    columns: [
      'landed_cost_no',
      'reference_no',
      'currency_code',
      'total_charge_amount',
      'status',
      'created_at',
    ],
    idCandidates: ['landed_cost_id', 'id'],
    attachmentEntityType: 'LANDED_COST',
    editableStatuses: ['DRAFT', 'REJECTED'],
    actions: [
      {
        operationId: 'Calculate',
        label: 'Calculate',
        permission: 'transaction.landed_costs.calculate',
        statuses: ['DRAFT', 'REJECTED'],
      },
      {
        operationId: 'Submit',
        label: 'Ajukan',
        permission: 'transaction.landed_costs.submit',
        statuses: ['DRAFT', 'REJECTED'],
      },
      {
        operationId: 'Approve',
        label: 'Setujui',
        permission: 'transaction.landed_costs.approve',
        statuses: ['SUBMITTED'],
      },
      {
        operationId: 'Reject',
        label: 'Tolak',
        permission: 'transaction.landed_costs.reject',
        statuses: ['SUBMITTED'],
        tone: 'danger',
      },
      {
        operationId: 'Post',
        label: 'Posting',
        permission: 'transaction.landed_costs.post',
        statuses: ['APPROVED'],
        confirm: 'Posting landed cost ke inventory costing?',
      },
      {
        operationId: 'Cancel',
        label: 'Batalkan',
        permission: 'transaction.landed_costs.cancel',
        statuses: ['DRAFT', 'REJECTED', 'SUBMITTED'],
        tone: 'danger',
      },
      {
        operationId: 'Reverse',
        label: 'Balikkan',
        permission: 'transaction.landed_costs.reverse',
        statuses: ['POSTED'],
        tone: 'danger',
      },
    ],
  }),

  stocks: crud({
    key: 'stocks',
    title: 'Saldo Stok',
    description: 'Posisi stok berdasarkan gudang, item, part, lot, dan UOM.',
    group: 'Inventory',
    route: '/inventory/stocks',
    listOperationId: 'FindAllStockBalances',
    readPermission: 'inventory.stocks.read',
    readOnly: true,
    columns: [
      'warehouse_name',
      'item_code',
      'item_name',
      'part_number',
      'lot_no',
      'uom_name',
      'qty_on_hand',
    ],
    idCandidates: ['stock_id', 'id'],
  }),
  'item-units': crud({
    key: 'item-units',
    title: 'Unit Barang & QR',
    description: 'Telusuri unit serial dan histori QR.',
    group: 'Inventory',
    route: '/inventory/item-units',
    listOperationId: 'FindAllItemUnits',
    readPermission: 'inventory.item_units.read',
    readOnly: true,
    columns: [
      'qr_code',
      'serial_number',
      'item_name',
      'part_number',
      'warehouse_name',
      'condition_status',
      'status',
    ],
    idCandidates: ['unit_id', 'id'],
    childSections: [
      {
        title: 'Riwayat Unit',
        operationId: 'FindItemUnitHistoryByID',
        permission: 'inventory.item_units.read',
      },
    ],
  }),
  'stock-thresholds': crud({
    key: 'stock-thresholds',
    title: 'Pengaturan Minimum Stok',
    description: 'Atur batas minimum stok per gudang dan item.',
    group: 'Inventory',
    route: '/inventory/stock-thresholds',
    listOperationId: 'FindStockThresholds',
    detailOperationId: 'FindStockThresholdByID',
    createOperationId: 'CreateStockThreshold',
    updateOperationId: 'UpdateStockThreshold',
    deleteOperationId: 'DeleteStockThreshold',
    readPermission: 'inventory.stock_thresholds.read',
    createPermission: 'inventory.stock_thresholds.create',
    updatePermission: 'inventory.stock_thresholds.update',
    deletePermission: 'inventory.stock_thresholds.delete',
    columns: ['warehouse_name', 'item_name', 'part_number', 'uom_name', 'minimum_qty', 'is_active'],
    idCandidates: ['threshold_id', 'id'],
  }),
  'low-stock': crud({
    key: 'low-stock',
    title: 'Barang dengan Stok Rendah',
    description: 'Barang yang berada di bawah batas stok minimum.',
    group: 'Inventory',
    route: '/inventory/low-stock',
    listOperationId: 'FindLowStockNotifications',
    readPermission: 'inventory.stock_thresholds.read',
    readOnly: true,
    columns: [
      'warehouse_name',
      'item_name',
      'part_number',
      'uom_name',
      'qty_on_hand',
      'minimum_qty',
      'shortage_qty',
    ],
    idCandidates: ['threshold_id', 'stock_id', 'id'],
  }),
  'item-requests': crud({
    key: 'item-requests',
    title: 'Permintaan Barang',
    description: 'Permintaan internal barang dari gudang tujuan.',
    group: 'Inventory',
    route: '/inventory/item-requests',
    listOperationId: 'FindAllItemRequests',
    detailOperationId: 'FindItemRequestByID',
    createOperationId: 'CreateItemRequest',
    updateOperationId: 'UpdateItemRequest',
    readPermission: 'transaction.item_requests.read',
    createPermission: 'transaction.item_requests.create',
    updatePermission: 'transaction.item_requests.update',
    columns: [
      'request_no',
      'requester_warehouse_name',
      'needed_date',
      'priority',
      'status',
      'created_at',
    ],
    idCandidates: ['request_id', 'id'],
    editableStatuses: ['DRAFT'],
    actions: [
      {
        operationId: 'SubmitItemRequest',
        label: 'Ajukan',
        permission: 'transaction.item_requests.submit',
        statuses: ['DRAFT'],
      },
      {
        operationId: 'CheckItemRequestStock',
        label: 'Cek Stok',
        permission: 'transaction.item_requests.check_stock',
        statuses: [
          'SUBMITTED',
          'APPROVED',
          'CHECKING_STOCK',
          'STOCK_AVAILABLE',
          'STOCK_UNAVAILABLE',
        ],
      },
      {
        operationId: 'ApproveItemRequest',
        label: 'Setujui',
        permission: 'transaction.item_requests.approve',
        statuses: ['SUBMITTED', 'STOCK_AVAILABLE', 'STOCK_UNAVAILABLE'],
      },
      {
        operationId: 'RejectItemRequest',
        label: 'Tolak',
        permission: 'transaction.item_requests.reject',
        statuses: ['SUBMITTED', 'STOCK_AVAILABLE', 'STOCK_UNAVAILABLE'],
        tone: 'danger',
      },
      {
        operationId: 'MarkItemRequestWaitingPurchase',
        label: 'Tunggu Pengadaan',
        permission: 'transaction.item_requests.mark_waiting_purchase',
        statuses: ['APPROVED'],
      },
      {
        operationId: 'CompleteItemRequest',
        label: 'Selesaikan',
        permission: 'transaction.item_requests.complete',
        statuses: ['FULFILLED', 'RECEIVED'],
      },
      {
        operationId: 'CancelItemRequest',
        label: 'Batalkan',
        permission: 'transaction.item_requests.cancel',
        hideStatuses: ['CANCELLED', 'COMPLETED', 'REJECTED'],
        tone: 'danger',
      },
    ],
    childSections: [
      {
        title: 'Ringkasan Pengiriman',
        operationId: 'GetItemRequestDeliverySummary',
        permission: 'transaction.item_requests.read',
      },
    ],
  }),
  'delivery-orders': crud({
    key: 'delivery-orders',
    title: 'Surat Jalan / Transfer Antar Gudang',
    description: 'Persiapan, scan keluar, pengiriman, dan penerimaan barang.',
    group: 'Inventory',
    route: '/inventory/delivery-orders',
    listOperationId: 'FindAllDeliveryOrders',
    detailOperationId: 'FindDeliveryOrderByID',
    createOperationId: 'CreateDeliveryOrder',
    readPermission: 'transaction.delivery_orders.read',
    createPermission: 'transaction.delivery_orders.create',
    updatePermission: 'transaction.delivery_orders.update',
    columns: [
      'delivery_no',
      'request_no',
      'from_warehouse_name',
      'to_warehouse_name',
      'tracking_no',
      'status',
      'created_at',
    ],
    idCandidates: ['delivery_id', 'delivery_order_id', 'id'],
    attachmentEntityType: 'DELIVERY_ORDER',
    actions: [
      {
        operationId: 'StartDeliveryOrderPicking',
        label: 'Mulai Picking',
        permission: 'transaction.delivery_orders.start_picking',
        statuses: ['DRAFT'],
        confirm: 'Mulai proses picking untuk Surat Jalan ini?',
      },
      {
        operationId: 'ConfirmDeliveryOrderPicking',
        label: 'Konfirmasi Picking',
        permission: 'transaction.delivery_orders.confirm_picking',
        statuses: ['PICKING'],
      },
      {
        operationId: 'ConfirmDeliveryOrderPacking',
        label: 'Konfirmasi Packing',
        permission: 'transaction.delivery_orders.confirm_packing',
        statuses: ['PACKING'],
      },
      {
        operationId: 'PreviewDeliveryOrderScanOut',
        label: 'Scan Keluar',
        permission: 'transaction.delivery_orders.scan_out',
        statuses: ['READY_TO_SHIP'],
        handler: 'delivery-order-scan-out',
      },
      {
        operationId: 'PreviewDeliveryOrderReceive',
        label: 'Scan Masuk',
        permission: 'transaction.delivery_orders.receive',
        statuses: ['SHIPPED', 'PARTIALLY_RECEIVED'],
        handler: 'delivery-order-scan-in',
      },
      {
        operationId: 'CancelDeliveryOrder',
        label: 'Batalkan',
        permission: 'transaction.delivery_orders.cancel',
        hideStatuses: ['RECEIVED_BY_DESTINATION', 'CANCELLED', 'REVERSED'],
        tone: 'danger',
      },
      {
        operationId: 'ReverseDeliveryOrder',
        label: 'Balikkan Penerimaan (Koreksi)',
        permission: 'transaction.delivery_orders.reverse',
        statuses: ['RECEIVED_BY_DESTINATION'],
        tone: 'danger',
      },
    ],
  }),
  'item-usages': crud({
    key: 'item-usages',
    title: 'Pengeluaran Berdasarkan Permintaan',
    description: 'Catat pengeluaran barang kepada pegawai, divisi, lokasi, atau kendaraan.',
    group: 'Inventory',
    route: '/inventory/item-usages',
    listOperationId: 'FindAllItemUsages',
    detailOperationId: 'FindItemUsageByID',
    createOperationId: 'CreateItemUsage',
    updateOperationId: 'UpdateItemUsage',
    readPermission: 'transaction.item_usages.read',
    createPermission: 'transaction.item_usages.create',
    updatePermission: 'transaction.item_usages.update',
    columns: [
      'usage_no',
      'warehouse_name',
      'responsibility_type',
      'responsibility_name',
      'usage_type',
      'status',
      'created_at',
    ],
    idCandidates: ['usage_id', 'id'],
    attachmentEntityType: 'ITEM_USAGE',
    editableStatuses: ['DRAFT'],
    actions: [
      {
        operationId: 'PreviewItemUsageScan',
        label: 'Pratinjau Pemindaian',
        permission: 'transaction.item_usages.scan',
        statuses: ['DRAFT'],
      },
      {
        operationId: 'PostItemUsage',
        label: 'Posting',
        permission: 'transaction.item_usages.post',
        statuses: ['DRAFT'],
      },
      {
        operationId: 'CancelItemUsage',
        label: 'Batalkan',
        permission: 'transaction.item_usages.cancel',
        hideStatuses: ['POSTED', 'CANCELLED', 'REVERSED'],
        tone: 'danger',
      },
      {
        operationId: 'ReverseItemUsage',
        label: 'Balikkan',
        permission: 'transaction.item_usages.reverse',
        statuses: ['POSTED'],
        tone: 'danger',
      },
    ],
  }),
  'stock-adjustments': crud({
    key: 'stock-adjustments',
    title: 'Penyesuaian Stok',
    description: 'Penyesuaian stok dengan approval dan posting.',
    group: 'Inventory',
    route: '/inventory/stock-adjustments',
    listOperationId: 'FindAllStockAdjustments',
    detailOperationId: 'FindStockAdjustmentByID',
    createOperationId: 'CreateStockAdjustment',
    readPermission: 'inventory.stock_adjustments.read',
    createPermission: 'inventory.stock_adjustments.create',
    updatePermission: 'inventory.stock_adjustments.update',
    columns: ['adjustment_no', 'warehouse_name', 'reason', 'status', 'created_at'],
    idCandidates: ['adjustment_id', 'id'],
    attachmentEntityType: 'STOCK_ADJUSTMENT',
    actions: [
      {
        operationId: 'ApproveStockAdjustment',
        label: 'Setujui',
        permission: 'inventory.stock_adjustments.approve',
        statuses: ['DRAFT'],
      },
      {
        operationId: 'PostStockAdjustment',
        label: 'Posting',
        permission: 'inventory.stock_adjustments.post',
        statuses: ['APPROVED'],
      },
      {
        operationId: 'CancelStockAdjustment',
        label: 'Batalkan',
        permission: 'inventory.stock_adjustments.cancel',
        hideStatuses: ['POSTED', 'CANCELLED', 'REVERSED'],
        tone: 'danger',
      },
      {
        operationId: 'ReverseStockAdjustment',
        label: 'Balikkan',
        permission: 'inventory.stock_adjustments.reverse',
        statuses: ['POSTED'],
        tone: 'danger',
      },
    ],
  }),
  'stock-opnames': crud({
    key: 'stock-opnames',
    title: 'Stok Opname',
    description: 'Buat, mulai, scan, review, dan posting stock opname.',
    group: 'Inventory',
    route: '/inventory/stock-opnames',
    listOperationId: 'FindAllStockOpnames',
    detailOperationId: 'FindStockOpnameByID',
    createOperationId: 'CreateStockOpname',
    readPermission: 'inventory.stock_opnames.read',
    createPermission: 'inventory.stock_opnames.create',
    updatePermission: 'inventory.stock_opnames.update',
    columns: ['opname_no', 'warehouse_name', 'status', 'started_at', 'posted_at', 'created_at'],
    idCandidates: ['opname_id', 'id'],
    attachmentEntityType: 'STOCK_OPNAME',
    actions: [
      {
        operationId: 'StartStockOpname',
        label: 'Start',
        permission: 'inventory.stock_opnames.start',
        statuses: ['DRAFT'],
      },
      {
        operationId: 'ScanStockOpname',
        label: 'Scan',
        permission: 'inventory.stock_opnames.scan',
        statuses: ['COUNTING'],
      },
      {
        operationId: 'ReviewStockOpname',
        label: 'Review',
        permission: 'inventory.stock_opnames.review',
        statuses: ['COUNTING'],
      },
      {
        operationId: 'PostStockOpname',
        label: 'Posting',
        permission: 'inventory.stock_opnames.post',
        statuses: ['REVIEWED'],
      },
      {
        operationId: 'CancelStockOpname',
        label: 'Batalkan',
        permission: 'inventory.stock_opnames.cancel',
        hideStatuses: ['POSTED', 'CANCELLED', 'REVERSED'],
        tone: 'danger',
      },
      {
        operationId: 'ReverseStockOpname',
        label: 'Balikkan',
        permission: 'inventory.stock_opnames.reverse',
        statuses: ['POSTED'],
        tone: 'danger',
      },
    ],
  }),
  'cost-balances': crud({
    key: 'cost-balances',
    title: 'Nilai Persediaan',
    description: 'Saldo nilai persediaan dan average cost.',
    group: 'Inventory',
    route: '/inventory/cost-balances',
    listOperationId: 'ListCostBalances',
    readPermission: 'inventory.cost_balances.read',
    readOnly: true,
    columns: [
      'warehouse_name',
      'item_name',
      'part_number',
      'uom_name',
      'qty_on_hand',
      'average_unit_cost',
      'total_cost',
      'currency_code',
    ],
    idCandidates: ['cost_balance_id', 'id'],
  }),
  'cost-movements': crud({
    key: 'cost-movements',
    title: 'Pergerakan Nilai',
    description: 'Riwayat pergerakan nilai persediaan.',
    group: 'Inventory',
    route: '/inventory/cost-movements',
    listOperationId: 'ListCostMovements',
    readPermission: 'inventory.cost_movements.read',
    readOnly: true,
    columns: [
      'movement_date',
      'movement_type',
      'reference_no',
      'item_name',
      'qty',
      'unit_cost',
      'total_cost',
      'currency_code',
    ],
    idCandidates: ['cost_movement_id', 'id'],
  }),

  assets: crud({
    key: 'assets',
    title: 'Semua Aset',
    description: 'Daftar, profil, assignment, maintenance, dan siklus hidup aset.',
    group: 'Asset',
    route: '/assets/register',
    listOperationId: 'FindAssets',
    detailOperationId: 'FindAssetByUnitID',
    updateOperationId: 'UpsertAssetProfile',
    readPermission: 'inventory.assets.read',
    updatePermission: 'inventory.assets.update',
    columns: [
      'asset_tag',
      'qr_code',
      'item_name',
      'serial_no',
      'condition_status',
      'assignment_status',
      'status',
    ],
    idCandidates: ['unit_id', 'id'],
    attachmentEntityType: 'ASSET',
    detailActions: [
      {
        operationId: 'AssignAsset',
        label: 'Assign',
        permission: 'inventory.asset_assignments.create',
        pathValueKey: 'unit_id',
      },
      {
        operationId: 'ReturnAsset',
        label: 'Return',
        permission: 'inventory.asset_assignments.return',
        pathValueKey: 'unit_id',
      },
      {
        operationId: 'TransferAsset',
        label: 'Transfer',
        permission: 'inventory.asset_assignments.transfer',
        pathValueKey: 'unit_id',
      },
      {
        operationId: 'CreateMaintenance',
        label: 'Perawatan',
        permission: 'inventory.asset_maintenances.create',
        pathValueKey: 'unit_id',
      },
      {
        operationId: 'ReportLoss',
        label: 'Lapor Hilang',
        permission: 'inventory.asset_losses.create',
        pathValueKey: 'unit_id',
        tone: 'danger',
      },
      {
        operationId: 'CreateDisposal',
        label: 'Disposal',
        permission: 'inventory.asset_disposals.create',
        pathValueKey: 'unit_id',
        tone: 'danger',
      },
      {
        operationId: 'CreateHandover',
        label: 'Berita Acara',
        permission: 'inventory.asset_handovers.create',
        pathValueKey: 'unit_id',
      },
    ],
    childSections: [
      {
        title: 'Riwayat Penugasan',
        operationId: 'FindAssignmentHistory',
        permission: 'inventory.asset_assignments.read',
        pathValueKey: 'unit_id',
      },
      {
        title: 'Penyusutan',
        operationId: 'GetDepreciation',
        permission: 'inventory.asset_depreciation.read',
        pathValueKey: 'unit_id',
      },
    ],
  }),
  'asset-assignments': crud({
    key: 'asset-assignments',
    title: 'Penugasan Aktif',
    description:
      'Daftar penugasan aset beserta penanggung jawab, kondisi, dan jadwal pengembalian.',
    group: 'Asset',
    route: '/assets/assignment-records',
    listOperationId: 'FindAssetAssignments',
    detailOperationId: 'FindAssetAssignmentByID',
    readPermission: 'inventory.asset_assignments.read',
    columns: [
      'assignment_no',
      'asset_tag',
      'item_name',
      'responsibility_type',
      'responsibility_name',
      'assignment_status',
      'assigned_at',
      'expected_return_at',
    ],
    idCandidates: ['assignment_id', 'id'],
    statusCandidates: ['assignment_status'],
    detailActions: [
      {
        operationId: 'ReturnAsset',
        label: 'Return',
        permission: 'inventory.asset_assignments.return',
        pathValueKey: 'unit_id',
        statuses: ['ACTIVE'],
      },
      {
        operationId: 'TransferAsset',
        label: 'Transfer',
        permission: 'inventory.asset_assignments.transfer',
        pathValueKey: 'unit_id',
        statuses: ['ACTIVE'],
      },
      {
        operationId: 'CreateHandover',
        label: 'Berita Acara',
        permission: 'inventory.asset_handovers.create',
        pathValueKey: 'unit_id',
      },
    ],
  }),
  'asset-maintenances': crud({
    key: 'asset-maintenances',
    title: 'Perawatan Aset',
    description: 'Pekerjaan maintenance aset.',
    group: 'Asset',
    route: '/assets/maintenances',
    listOperationId: 'FindMaintenances',
    detailOperationId: 'FindMaintenanceByID',
    readPermission: 'inventory.asset_maintenances.read',
    updatePermission: 'inventory.asset_maintenances.update',
    columns: [
      'maintenance_no',
      'asset_tag',
      'item_name',
      'maintenance_type',
      'maintenance_status',
      'started_at',
      'completed_at',
    ],
    idCandidates: ['maintenance_id', 'id'],
    statusCandidates: ['maintenance_status'],
    attachmentEntityType: 'ASSET_MAINTENANCE',
    actions: [
      {
        operationId: 'StartMaintenance',
        label: 'Start',
        permission: 'inventory.asset_maintenances.start',
        statuses: ['OPEN'],
      },
      {
        operationId: 'CompleteMaintenance',
        label: 'Complete',
        permission: 'inventory.asset_maintenances.complete',
        statuses: ['IN_PROGRESS'],
      },
      {
        operationId: 'CancelMaintenance',
        label: 'Batalkan',
        permission: 'inventory.asset_maintenances.cancel',
        hideStatuses: ['COMPLETED', 'CANCELLED'],
        tone: 'danger',
      },
    ],
  }),
  'asset-losses': crud({
    key: 'asset-losses',
    title: 'Kerusakan & Kehilangan Aset',
    description: 'Catat kerusakan, kehilangan, investigasi, pemulihan, dan penyelesaiannya.',
    group: 'Asset',
    route: '/assets/loss-cases',
    listOperationId: 'ListLossCases',
    detailOperationId: 'FindLossCase',
    readPermission: 'inventory.asset_losses.read',
    columns: ['loss_no', 'asset_tag', 'item_name', 'loss_date', 'status'],
    idCandidates: ['loss_case_id', 'id'],
    attachmentEntityType: 'ASSET_LOSS',
    actions: [
      {
        operationId: 'ReviewLoss',
        label: 'Review',
        permission: 'inventory.asset_losses.review',
        statuses: ['REPORTED'],
      },
      {
        operationId: 'ApproveLoss',
        label: 'Setujui',
        permission: 'inventory.asset_losses.approve',
        statuses: ['UNDER_REVIEW'],
      },
      {
        operationId: 'RejectLoss',
        label: 'Tolak',
        permission: 'inventory.asset_losses.reject',
        hideStatuses: ['CLOSED', 'RECOVERED', 'REJECTED'],
        tone: 'danger',
      },
      {
        operationId: 'RecoverLoss',
        label: 'Recover',
        permission: 'inventory.asset_losses.recover',
        statuses: ['APPROVED', 'UNDER_REVIEW'],
      },
      {
        operationId: 'CloseLoss',
        label: 'Close',
        permission: 'inventory.asset_losses.close',
        statuses: ['APPROVED'],
      },
    ],
  }),
  'asset-disposals': crud({
    key: 'asset-disposals',
    title: 'Disposal / Penghapusan Aset',
    description: 'Approval dan penyelesaian disposal/write-off aset.',
    group: 'Asset',
    route: '/assets/disposals',
    listOperationId: 'ListDisposals',
    detailOperationId: 'FindDisposal',
    readPermission: 'inventory.asset_disposals.read',
    columns: ['disposal_no', 'asset_tag', 'item_name', 'disposal_method', 'requested_at', 'status'],
    idCandidates: ['disposal_id', 'id'],
    attachmentEntityType: 'ASSET_DISPOSAL',
    actions: [
      {
        operationId: 'SubmitDisposal',
        label: 'Ajukan',
        permission: 'inventory.asset_disposals.submit',
        statuses: ['DRAFT'],
      },
      {
        operationId: 'ApproveDisposal',
        label: 'Setujui',
        permission: 'inventory.asset_disposals.approve',
        statuses: ['SUBMITTED'],
      },
      {
        operationId: 'RejectDisposal',
        label: 'Tolak',
        permission: 'inventory.asset_disposals.reject',
        statuses: ['SUBMITTED'],
        tone: 'danger',
      },
      {
        operationId: 'CompleteDisposal',
        label: 'Complete',
        permission: 'inventory.asset_disposals.complete',
        statuses: ['APPROVED'],
      },
    ],
  }),
  'asset-depreciation': crud({
    key: 'asset-depreciation',
    title: 'Penyusutan Aset',
    description: 'Laporan dan snapshot penyusutan aset.',
    group: 'Asset',
    route: '/assets/depreciation',
    listOperationId: 'ListDepreciation',
    readPermission: 'inventory.asset_depreciation.read',
    readOnly: true,
    columns: [
      'asset_tag',
      'item_name',
      'purchase_cost',
      'accumulated_depreciation',
      'book_value',
      'as_of_date',
    ],
    idCandidates: ['unit_id', 'id'],
    actions: [
      {
        operationId: 'SnapshotDepreciation',
        label: 'Buat Snapshot',
        permission: 'inventory.asset_depreciation.snapshot',
      },
    ],
  }),
  'asset-handovers': crud({
    key: 'asset-handovers',
    title: 'Berita Acara Aset',
    description: 'Dokumen serah terima dan tanda tangan aset.',
    group: 'Asset',
    route: '/assets/handovers',
    listOperationId: 'ListHandovers',
    detailOperationId: 'FindHandover',
    readPermission: 'inventory.asset_handovers.read',
    columns: ['document_no', 'document_type', 'title', 'status', 'signed_by_name', 'created_at'],
    idCandidates: ['handover_id', 'document_id', 'id'],
    attachmentEntityType: 'HANDOVER_DOCUMENT',
    actions: [
      {
        operationId: 'PrintHandover',
        label: 'Cetak',
        permission: 'inventory.asset_handovers.read',
        openHtmlPath: '/api/v1/handover-documents/{id}/print',
      },
      {
        operationId: 'SignHandover',
        label: 'Sign',
        permission: 'inventory.asset_handovers.sign',
        hideStatuses: ['SIGNED'],
      },
    ],
  }),

  notifications: crud({
    key: 'notifications',
    title: 'Notifikasi',
    description: 'Notifikasi operasional, low stock, dan approval.',
    group: 'Operasional',
    route: '/operations/notifications',
    listOperationId: 'ListNotifications',
    readPermission: 'operations.notifications.read',
    readOnly: true,
    columns: ['notification_type', 'title', 'message', 'severity', 'is_read', 'created_at'],
    idCandidates: ['notification_id', 'id'],
    actions: [
      {
        operationId: 'RunNotificationScan',
        label: 'Jalankan Pemindaian',
        permission: 'operations.notifications.run',
        confirm: 'Jalankan scheduler notifikasi sekarang?',
      },
      {
        operationId: 'MarkNotificationRead',
        label: 'Tandai Dibaca',
        permission: 'operations.notifications.update',
      },
      {
        operationId: 'DismissNotification',
        label: 'Dismiss',
        permission: 'operations.notifications.update',
        tone: 'danger',
      },
    ],
  }),
  users: crud({
    key: 'users',
    title: 'Users',
    description: 'Kelola akun, status, akses context, role, password, dan session.',
    group: 'Administrasi',
    route: '/administration/users',
    listOperationId: 'FindAllUsers',
    detailOperationId: 'FindUserByID',
    createOperationId: 'CreateUser',
    updateOperationId: 'UpdateUser',
    deleteOperationId: 'DeleteUser',
    superAdminOnly: true,
    readPermission: 'auth.users.read',
    createPermission: 'auth.users.create',
    updatePermission: 'auth.users.update',
    deletePermission: 'auth.users.delete',
    columns: ['nib', 'full_name', 'email', 'is_active', 'last_login_at', 'created_at'],
    idCandidates: ['user_id', 'id'],
    detailActions: [
      {
        operationId: 'SetUserStatus',
        label: 'Ubah Status',
        group: 'Akun & Keamanan',
        permission: 'auth.users.update_status',
      },
      {
        operationId: 'UpdateUserPassword',
        label: 'Ubah Password',
        group: 'Akun & Keamanan',
        permission: 'auth.users.update_password',
      },
      {
        operationId: 'RevokeUserSessions',
        label: 'Cabut Session',
        group: 'Akun & Keamanan',
        permission: 'auth.users.revoke_sessions',
        confirm: 'Cabut seluruh session aktif user ini?',
        tone: 'danger',
      },
      {
        operationId: 'SetUserAccess',
        label: 'Atur Akses',
        group: 'Hak Akses',
        permission: 'auth.users.access.update',
      },
      {
        operationId: 'AssignUserCategoryGroups',
        label: 'Atur Kelompok Kategori',
        group: 'Hak Akses',
        permission: 'auth.users.access.update',
      },
      {
        operationId: 'AssignUserRoles',
        label: 'Atur Peran',
        group: 'Hak Akses',
        permission: 'auth.users.roles.update',
      },
    ],
  }),
  roles: crud({
    key: 'roles',
    title: 'Peran',
    description: 'Kelola role dan assignment permission.',
    group: 'Administrasi',
    route: '/administration/roles',
    listOperationId: 'FindAllRoles',
    detailOperationId: 'FindRoleByID',
    createOperationId: 'CreateRole',
    updateOperationId: 'UpdateRole',
    deleteOperationId: 'DeleteRole',
    superAdminOnly: true,
    readPermission: 'auth.roles.read',
    createPermission: 'auth.roles.create',
    updatePermission: 'auth.roles.update',
    deletePermission: 'auth.roles.delete',
    columns: ['code', 'name', 'description', 'is_system', 'created_at'],
    idCandidates: ['role_id', 'id'],
    detailActions: [
      {
        operationId: 'AssignRolePermissions',
        label: 'Atur Izin',
        permission: 'auth.roles.permissions.update',
      },
    ],
    childSections: [
      {
        title: 'Izin Peran',
        operationId: 'FindRolePermissions',
        permission: 'auth.roles.permissions.read',
      },
    ],
  }),
  permissions: crud({
    key: 'permissions',
    title: 'Izin',
    description: 'Daftar permission backend dan pengelolaan RBAC.',
    group: 'Administrasi',
    route: '/administration/permissions',
    listOperationId: 'FindAllPermissions',
    detailOperationId: 'FindPermissionByID',
    createOperationId: 'CreatePermission',
    updateOperationId: 'UpdatePermission',
    deleteOperationId: 'DeletePermission',
    superAdminOnly: true,
    readPermission: 'auth.permissions.read',
    createPermission: 'auth.permissions.create',
    updatePermission: 'auth.permissions.update',
    deletePermission: 'auth.permissions.delete',
    columns: ['code', 'name', 'description', 'created_at'],
    idCandidates: ['permission_id', 'id'],
  }),
  'audit-logs': crud({
    key: 'audit-logs',
    title: 'Audit Logs',
    description: 'Riwayat perubahan data oleh user.',
    group: 'Administrasi',
    route: '/administration/audit-logs',
    listOperationId: 'FindAuditLogs',
    readPermission: 'auth.activity.audit_logs.read',
    superAdminOnly: true,
    readOnly: true,
    columns: ['created_at', 'actor_name', 'action', 'entity_type', 'entity_id', 'ip_address'],
    idCandidates: ['audit_log_id', 'audit_id', 'id'],
  }),
  'login-histories': crud({
    key: 'login-histories',
    title: 'Login Histories',
    description: 'Riwayat login berhasil dan gagal.',
    group: 'Administrasi',
    route: '/administration/login-histories',
    listOperationId: 'FindLoginHistories',
    readPermission: 'auth.activity.login_histories.read',
    superAdminOnly: true,
    readOnly: true,
    columns: ['created_at', 'email', 'user_name', 'success', 'ip_address', 'device_name'],
    idCandidates: ['login_history_id', 'id'],
  }),
  'active-sessions': crud({
    key: 'active-sessions',
    title: 'Active Sessions',
    description: 'Session user yang masih aktif.',
    group: 'Administrasi',
    route: '/administration/active-sessions',
    listOperationId: 'FindActiveSessions',
    readPermission: 'auth.activity.active_sessions.read',
    superAdminOnly: true,
    readOnly: true,
    columns: ['user_name', 'email', 'device_name', 'ip_address', 'created_at', 'expires_at'],
    idCandidates: ['refresh_token_id', 'session_id', 'id'],
  }),

  'stock-reconciliation': crud({
    key: 'stock-reconciliation',
    title: 'Rekonsiliasi Stok',
    description: 'Periksa integritas saldo dan pergerakan stok.',
    group: 'Maintenance',
    route: '/maintenance/stock-reconciliation',
    listOperationId: 'ReconcileStock',
    readPermission: 'maintenance.stock_reconciliation.read',
    readOnly: true,
    columns: ['warehouse_name', 'item_name', 'balance_qty', 'movement_qty', 'difference'],
    idCandidates: ['stock_id', 'id'],
  }),
  'cost-reconciliation': crud({
    key: 'cost-reconciliation',
    title: 'Rekonsiliasi Biaya',
    description: 'Periksa selisih saldo stok dan inventory costing.',
    group: 'Maintenance',
    route: '/maintenance/cost-reconciliation',
    listOperationId: 'GetCostReconciliation',
    readPermission: 'maintenance.cost_reconciliation.read',
    readOnly: true,
    columns: [
      'warehouse_name',
      'item_name',
      'stock_qty',
      'cost_qty',
      'stock_value',
      'cost_value',
      'difference',
    ],
    idCandidates: ['cost_balance_id', 'id'],
    actions: [
      {
        operationId: 'RunCostReconciliation',
        label: 'Jalankan Rekonsiliasi',
        permission: 'maintenance.cost_reconciliation.run',
        confirm: 'Jalankan rekonsiliasi biaya sekarang?',
      },
    ],
  }),
}

export const resourceModuleList = Object.values(resourceModules)
