const statusLabels: Record<string, string> = {
  ACTIVE: 'Aktif',
  INACTIVE: 'Tidak Aktif',
  DRAFT: 'Draf',
  NEW: 'Baru',
  SUBMITTED: 'Diajukan',
  UNDER_REVIEW: 'Sedang Ditinjau',
  APPROVED: 'Disetujui',
  REJECTED: 'Ditolak',
  CANCELLED: 'Dibatalkan',
  COMPLETED: 'Selesai',
  CLOSED: 'Ditutup',
  POSTED: 'Sudah Diposting',
  POSTED_TO_STOCK: 'Sudah Masuk Stok',
  REVERSED: 'Dibatalkan Balik',
  RECEIVED: 'Diterima',
  CHECKING: 'Sedang Diperiksa',
  CHECKED: 'Sudah Diperiksa',
  ACCEPTED: 'Diterima',
  PARTIAL_ACCEPTED: 'Diterima Sebagian',
  PARTIALLY_RECEIVED: 'Diterima Sebagian',
  RECEIVED_BY_DESTINATION: 'Diterima Gudang Tujuan',
  READY: 'Siap',
  READY_TO_SHIP: 'Siap Dikirim',
  PICKING: 'Pengambilan Barang',
  PACKING: 'Pengemasan',
  SHIPPED: 'Dikirim',
  IN_TRANSIT: 'Dalam Perjalanan',
  AVAILABLE: 'Tersedia',
  ASSIGNED: 'Ditugaskan',
  RETURNED: 'Dikembalikan',
  LOST: 'Hilang',
  DAMAGED: 'Rusak',
  UNUSABLE: 'Tidak Dapat Digunakan',
  DISPOSED: 'Dilepas',
  MAINTENANCE: 'Perawatan',
  IN_PROGRESS: 'Sedang Diproses',
  PENDING: 'Menunggu',
  PARTIAL: 'Sebagian',
  VALID: 'Valid',
  INVALID: 'Tidak Valid',
  FAILED: 'Gagal',
  SUCCESS: 'Berhasil',
  LOW: 'Rendah',
  NORMAL: 'Normal',
  HIGH: 'Tinggi',
  URGENT: 'Mendesak',
  STOCK_AVAILABLE: 'Stok Tersedia',
  STOCK_UNAVAILABLE: 'Stok Tidak Tersedia',
  CHECKING_STOCK: 'Sedang Memeriksa Stok',
  WAITING_PURCHASE: 'Menunggu Pengadaan',
  WAITING_STOCK: 'Menunggu Stok',
  PROCESSING_DELIVERY: 'Sedang Diproses untuk Pengiriman',
  PARTIALLY_FULFILLED: 'Terpenuhi Sebagian',
  FULFILLED: 'Terpenuhi',
  SENT_TO_VENDOR: 'Dikirim ke Pemasok',
  VENDOR_PROCESSING: 'Diproses Pemasok',
  INDENT: 'Inden',
  COUNTING: 'Sedang Dihitung',
  PREVIEWED: 'Sudah Dipratinjau',
  COMMITTED: 'Dikomitmenkan',
  RESOLVED: 'Terselesaikan',
  RECOVERED: 'Dipulihkan',
  SIGNED: 'Ditandatangani',
  REPLACEMENT_PROCESS: 'Proses Penggantian',
  REPLACEMENT_SHIPPED: 'Pengganti Dikirim',
  APPROVED_RETURN: 'Retur Disetujui',
  GOOD: 'Baik',
  FAIR: 'Cukup',
}

export function indonesianStatus(value: unknown): string {
  const normalized = String(value ?? 'UNKNOWN')
    .trim()
    .toUpperCase()
  if (normalized === 'UNKNOWN') return 'Tidak Diketahui'
  return statusLabels[normalized] ?? normalized.replaceAll('_', ' ')
}
